// File generated by FlutterFire CLI.
// ignore_for_file: lines_longer_than_80_chars, avoid_classes_with_only_static_members
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for macos - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyCBCu-SUn8i9XOJ_ry5rDeCaRqqoQWRc2c',
    appId: '1:242385400274:web:53f6815fd1d4de0a17180b',
    messagingSenderId: '242385400274',
    projectId: 'blood-app-f9d9c',
    authDomain: 'blood-app-f9d9c.firebaseapp.com',
    storageBucket: 'blood-app-f9d9c.appspot.com',
    measurementId: 'G-463HGTYDRY',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyCAVXZjZgMvxWoCDertZv1vYaAHDpdAiLQ',
    appId: '1:242385400274:android:01c1e88a403ece2d17180b',
    messagingSenderId: '242385400274',
    projectId: 'blood-app-f9d9c',
    storageBucket: 'blood-app-f9d9c.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyBEbmSpINtqQKhU47HRW7b4o3a0riohw8s',
    appId: '1:242385400274:ios:c2611b099f8de0cb17180b',
    messagingSenderId: '242385400274',
    projectId: 'blood-app-f9d9c',
    storageBucket: 'blood-app-f9d9c.appspot.com',
    iosBundleId: 'com.example.bloodApp',
  );
}
